In [2]:
#check pandas version
import pandas as pd
print(pd.__version__)

1.5.2

In [4]:
#Series
import pandas as pd
a=[11,12,2,34,56,78,89,90]
myvar= pd.Series(a)
print(myvar)

0    11
1    12
2     2
3    34
4    56
5    78
6    89
7    90
dtype: int64

In [5]:
#access element in Series
print(myvar[3])
#by default 0-7 index numbers given as a label

34

In [7]:
#let's create own labels
import pandas as pd
a=[1,7,4]
myvar=pd.Series(a,index=["a","b","c"])
print(myvar)
print(myvar["b"])

a    1
b    7
c    4
dtype: int64
7

In [10]:
import pandas as pd
studentObject= {"id":1,"name":"sonam","email":"sonam@gmail.com"} #dictionary object in Series
s1= pd.Series(studentObject)
print(s1) #see id,name and email become labels
print("Id: ",s1["id"])
print("Name: ",s1["name"])
print("Email: ",s1["email"])

id                     1
name               sonam
email    sonam@gmail.com
dtype: object
Id:  1
Name:  sonam
Email:  sonam@gmail.com

In [18]:
#dataframes
import pandas as pd
data={
    "name":["alex","bob","catty","david"],
    "age" : [30,23,34,28]
}

myvar= pd.DataFrame(data)
print(myvar)
#you want to get the row then use loc attribute
print("First Row")
print(myvar.loc[0])
#get first 2 rows
print(myvar.loc[[0,1]])

    name  age
0   alex   30
1    bob   23
2  catty   34
3  david   28
First Row
name    alex
age       30
Name: 0, dtype: object
   name  age
0  alex   30
1   bob   23

In [19]:
#dataframes
import pandas as pd
data={
    "name":["alex","bob","catty","david"],
    "age" : [30,23,34,28]
}

myvar= pd.DataFrame(data, index=["u1","u2","u3","u4"])
print(myvar)
#you want to get the row then use loc attribute
print("First Row")
print(myvar.loc["u3"])

     name  age
u1   alex   30
u2    bob   23
u3  catty   34
u4  david   28
First Row
name    catty
age        34
Name: u3, dtype: object

In [23]:
import pandas as pd
data={
    "name":["alex","bob","catty","david"],
    "age" : [30,23,34,28]
}

myvar= pd.DataFrame(data, columns=['name','age'])
print(myvar)

    name  age
0   alex   30
1    bob   23
2  catty   34
3  david   28

In [26]:
import pandas as pd
df= pd.read_csv('files/csvdata.csv')
print(df)

            name              Model  ModelYear   Price
0         Suzuki      Daewoo Magnus       2005  192628
1         Jaguar                 XJ       2006  184629
2          Lexus          RX Hybrid       2011  131097
3     Land Rover  Range Rover Sport       2009  152219
4    Rolls-Royce            Phantom       2005  183878
..           ...                ...        ...     ...
995          Kia              Forte       2012  101292
996    Chevrolet               2500       1994  161938
997   Alfa Romeo                164       1993  133329
998         Ford           Explorer       1998  130946
999    Chevrolet       G-Series G10       1994  199541

[1000 rows x 4 columns]

In [27]:
print(df.to_string())

              name                    Model  ModelYear   Price
0           Suzuki            Daewoo Magnus       2005  192628
1           Jaguar                       XJ       2006  184629
2            Lexus                RX Hybrid       2011  131097
3       Land Rover        Range Rover Sport       2009  152219
4      Rolls-Royce                  Phantom       2005  183878
5        Chevrolet                   Impala       2010  170121
6         Infiniti                      G25       2011  196625
7       Volkswagen                  Eurovan       2003  147186
8            Dodge                  Charger       2008  169119
9         Cadillac             Escalade EXT       2012  106542
10           Honda                    Pilot       2011  149047
11           Dodge                  Stratus       2004  121605
12             GMC                    Envoy       2004  108310
13           Lexus                       LX       2007  120714
14           Mazda                     MX-6       1990  169285
15           Honda                    Civic       1989  110939
16            Ford                    Probe       1993  189452
17         Pontiac                     1000       1984  137358
18      Land Rover                      LR2       2011  159466
19             BMW                       M5       2001  164594
20    Aston Martin                      DB9       2007  198199
21            Ford                 F-Series       1990  177258
22            Ford                     F150       1984  136419
23          Toyota               FJ Cruiser       2011  174334
24         Lincoln                      MKS       2013  135230
25            MINI           Cooper Clubman       2011  161379
26           Isuzu                  Trooper       2000  164768
27          Subaru               B9 Tribeca       2006  102005
28            Ford                   Ranger       2005  107672
29         Mercury                    Topaz       1991  100361
30           Buick                  Century       1997  103638
31             BMW                      545       2005  178496
32           Dodge               Ramcharger       1992  159763
33        Chrysler                 Concorde       2004  151268
34          Toyota              Tacoma Xtra       2002  100107
35      Mitsubishi         Lancer Evolution       2003  186289
36        Maserati             Quattroporte       2010  111819
37           Lotus                   Esprit       1998  165670
38       Chevrolet                 Citation       1980  140881
39        Cadillac            Sixty Special       1993  136441
40        Chrysler                Crossfire       2008  131074
41           Lexus                       LX       2009  137202
42           Scion                       tC       2010  128174
43             GMC         Rally Wagon 3500       1993  151310
44      Mitsubishi                  Montero       1994  139339
45         Lincoln                Blackwood       2003  165566
46          Toyota                     Echo       2005  190174
47           Dodge                   Shadow       1994  178067
48           Dodge                D350 Club       1993  198715
49            Ford                   Taurus       2009  101993
50            Audi                       TT       2002  143922
51             GMC                   Safari       1999  107484
52            Saab                      9-3       2011  103466
53            Audi                   riolet       1995  179068
54            Ford                  Mustang       1968  157497
55           Buick                  LeSabre       2004  131946
56            Ford           Econoline E250       1996  122178
57   Mercedes-Benz                  SLS AMG       2011  152787
58             GMC         Savana Cargo Van       2006  157161
59         Pontiac                      GTO       1965  188021
60        Plymouth                    Laser       1991  134524
61       Chevrolet             G-Series G30       1995  188368
62      Volkswagen                   Passat       2008  121821
63          Suzuki                       SJ       1987  126104
64           Lexus                       LS       2004  140398
65          Toyota                    Camry       2000  147369
66             GMC            Vandura G3500       1996  103274
67   Mercedes-Benz                SLK55 AMG       2009  147994
68         Lincoln              Continental       1991  100972
69            Ford                   Ranger       2011  158871
70      Land Rover              Range Rover       1999  104920
71          Toyota                    Prius       2001  192880
72       Chevrolet           Silverado 1500       2010  187856
73       Chevrolet             G-Series G20       1994  103501
74          Toyota                      MR2       1987  174602
75         Ferrari                     F430       2007  117925
76          Toyota                  Corolla       2008  124210
77        Infiniti                       EX       2009  147978
78            Audi                       S5       2008  104154
79         Pontiac               Bonneville       1964  142233
80            Ford           Econoline E250       1992  179929
81             GMC            Yukon XL 2500       2011  155388
82         Mercury                 Monterey       2005  134673
83         Pontiac                 Grand Am       1986  123803
84            Ford                 E-Series       2007  175699
85           Smart                   Fortwo       2011  112490
86      Land Rover                 Defender       1995  181154
87          Nissan                    Titan       2008  193056
88          Toyota                   Avalon       1999  149117
89             BMW                       X6       2008  189581
90         Porsche                      944       1990  100335
91            Audi                       A3       2006  157636
92            Ford                      ZX2       2001  162410
93           Lexus                       IS       2008  158780
94        Plymouth                     Neon       1999  147620
95       Chevrolet             Express 1500       2011  170676
96          Subaru                    Justy       1992  136577
97          Nissan                   Sentra       1996  161003
98         Lincoln                 Town Car       2007  125479
99      Oldsmobile                       88       1992  195453
100  Mercedes-Benz                SLK-Class       2008  167155
101      Chevrolet             Sportvan G20       1995  153271
102       Infiniti                        G       1999  155207
103       Infiniti                      G35       2003  105037
104        Lincoln              Continental       1998  185157
105          Volvo                      S80       2003  165119
106            GMC                    Yukon       2010  129583
107    Rolls-Royce                    Ghost       2010  183425
108          Acura                       TL       2004  133599
109          Buick               Roadmaster       1993  170125
110        Hyundai                  Tiburon       1999  149482
111           Ford                     F250       2010  148864
112          Buick               Rendezvous       2005  166978
113        Pontiac                 Grand Am       1992  199065
114  Mercedes-Benz                  E-Class       1992  184870
115            Kia                  Sorento       2011  162494
116          Volvo                      V50       2005  189992
117            BMW                       Z3       1996  183228
118          Volvo                      V70       2008  150099
119         Jaguar                XK Series       2002  130843
120         Hummer                       H3       2006  184484
121        Mercury                   Tracer       1988  167203
122      Chevrolet                K5 Blazer       1995  139481
123        Pontiac               Bonneville       2003  101618
124     Volkswagen                Cabriolet       2000  157313
125          Dodge             Ram Van 3500       2003  146831
126        Bentley                   Arnage       2008  103845
127          Lexus                       LS       1997  157197
128          Lexus                       SC       1998  155971
129        Maybach                       57       2011  117198
130          Isuzu                 Ascender       2005  158230
131     Volkswagen                 Golf III       1995  127884
132      Chevrolet                  Equinox       2011  177882
133      Chevrolet                    Astro       1999  198005
134           Saab                      900       1993  185778
135            Kia                  Spectra       2004  114753
136       Chrysler                 Pacifica       2006  153989
137            BMW                       M5       2002  133739
138          Lexus                       SC       1994  153701
139           Ford             C-MAX Hybrid       2013  151926
140          Buick                  Century       1998  119425
141         Suzuki                    Swift       2005  105618
142          Lotus                    Exige       2011  179080
143          Isuzu                    i-350       2006  129923
144          Volvo                     XC90       2006  196809
145        Pontiac                      GTO       1970  103446
146           MINI                   Cooper       2002  176237
147      Chevrolet                   Camaro       1992  102558
148           Ford                     E350       2011  158421
149       Maserati             Quattroporte       2006  141693
150       Plymouth                     Neon       2001  101222
151         Nissan                    200SX       1996  156500
152        Pontiac                      GTO       1971  127743
153        Hyundai                  Elantra       2010  115644
154        Pontiac                   LeMans       1964  121931
155            GMC                     1500       1994  106119
156            BMW                      600       1957  197901
157          Mazda                     MX-5       1998  195046
158          Lexus                       IS       2004  173579
159     Volkswagen               New Beetle       2007  170367
160        Porsche                  Boxster       2000  120751
161           Ford                  Contour       2000  126923
162          Honda                  Odyssey       2001  139475
163          Mazda                     CX-7       2010  159776
164          Dodge             Ram Van 2500       1997  113929
165         Jaguar                   S-Type       2005  199070
166            Kia                   Sedona       2010  128474
167       Infiniti                        M       2012  165655
168           Ford                     F350       2002  126505
169           Saab                     9-4X       2011  121939
170     Volkswagen                  Corrado       1991  157067
171     Oldsmobile                   Aurora       1995  175298
172           Audi                   5000CS       1987  190326
173         Nissan                   Maxima       2004  178506
174        Porsche                      928       1989  172937
175            BMW                       M6       2008  154350
176      Chevrolet           Silverado 3500       2004  171119
177      Chevrolet                Avalanche       2009  166927
178      Chevrolet                    Astro       2003  143199
179         Jaguar                   X-Type       2004  113636
180        Porsche                      911       1993  191490
181        Bentley           Continental GT       2008  130761
182          Buick                  Century       2005  193542
183           Ford                   Ranger       1999  117531
184          Dodge                   Dakota       2004  115499
185         Toyota               FJ Cruiser       2007  163365
186        Hyundai                   Accent       2004  142804
187           Ford               Expedition       2000  115749
188        Hyundai            Genesis Coupe       2010  169892
189   Aston Martin                      DB9       2006  132684
190            Kia                  Spectra       2003  168510
191        Pontiac               Grand Prix       2006  184520
192            GMC              Sierra 1500       2000  184607
193        Lincoln              Continental       2000  169670
194      Chevrolet              TrailBlazer       2002  187560
195        Bentley          Continental GTC       2010  179452
196          Acura                      TSX       2005  107432
197            GMC          1500 Club Coupe       1995  140803
198       Infiniti                      G37       2008  110598
199          Buick                  Riviera       1996  114581
200          Honda                    Civic       1998  118002
201          Dodge                      Ram       2010  143808
202          Honda                    Civic       1994  157481
203         Saturn                      Ion       2004  134685
204           Ford                   Taurus       2003  183515
205       Cadillac                      CTS       2008  179576
206        Pontiac                 Grand Am       2002  152086
207        Mercury            Grand Marquis       2004  136861
208      Chevrolet             Express 1500       2008  133098
209        Pontiac                     1000       1984  175995
210     Mitsubishi                      RVR       1992  111232
211       Maserati                  Biturbo       1986  139603
212     Volkswagen                  Touareg       2009  164663
213          Dodge                     Omni       1978  197633
214          Dodge            Ram 3500 Club       1997  100107
215     Land Rover                Discovery       2002  122296
216        Pontiac               Grand Prix       1987  135910
217       Chrysler                  Sebring       2000  172523
218          Honda                  Insight       2000  100436
219  Mercedes-Benz                 CL-Class       2011  193416
220        Hyundai                 Santa Fe       2008  193031
221            Ram                     3500       2011  125513
222          Eagle                   Summit       1993  146897
223           Ford               Club Wagon       1996  174721
224     Volkswagen                      rio       1998  149947
225      Chevrolet                  Caprice       1996  114572
226     Volkswagen                 Scirocco       1988  161287
227        Bentley          Continental GTC       2007  137287
228         Daewoo                   Nubira       2001  121363
229     Volkswagen                   Tiguan       2012  176017
230      Chevrolet          Caprice Classic       1994  128749
231     Mitsubishi                  Montero       2004  111573
232            GMC                   Canyon       2006  187367
233            GMC                     3500       1996  173753
234      Chevrolet                 Cavalier       2003  192548
235         Toyota                   Celica       1976  179524
236           Ford           Econoline E250       1995  177888
237     Mitsubishi                  Chariot       1990  179377
238     Oldsmobile                  Bravada       1996  178159
239           Ford       LTD Crown Victoria       1991  115070
240           Ford           Crown Victoria       2009  190482
241           Ford                     F250       2006  171801
242          Dodge                 Ram 1500       2006  108485
243          Volvo                      C70       2000  104400
244          Mazda                      MPV       1990  121003
245      Chevrolet                Avalanche       2011  143777
246          Acura                       RL       1997  174429
247         Toyota                  Prius v       2012  187552
248          Isuzu                    Rodeo       1994  177143
249     Mitsubishi                   Pajero       1994  147111
250     Mitsubishi                Outlander       2006  128911
251            GMC                    Yukon       1993  102426
252     Land Rover                      LR2       2010  131944
253          Acura                       TL       2008  107849
254      Chevrolet                  Tracker       2001  105018
255        Porsche                      924       1988  192663
256        Mercury            Grand Marquis       1990  130606
257            BMW                 7 Series       1993  102440
258          Lexus                       GS       2004  117525
259  Mercedes-Benz                     W201       1989  147873
260        Hyundai                  Elantra       2011  134140
261  Mercedes-Benz                  E-Class       2002  110136
262       Maserati                  Biturbo       1985  145270
263            GMC            Yukon XL 1500       2010  114733
264     Oldsmobile                  Achieva       1997  133204
265         Subaru                   Legacy       1997  188799
266         Toyota                   Solara       2006  122508
267     Land Rover      Discovery Series II       2002  120905
268            GMC            Suburban 2500       1997  149054
269     Volkswagen                Cabriolet       1992  111174
270            BMW                      745       2004  198347
271        Hyundai                   Sonata       1993  127354
272     Land Rover              Range Rover       2010  173525
273       Plymouth            Grand Voyager       1998  107438
274        Porsche                      928       1991  109735
275          Lotus                   Esprit       1988  153001
276  Mercedes-Benz                SLK-Class       2002  128645
277          Lexus                       GS       2004  135369
278       Chrysler                      300       2009  184435
279          Lexus                       LS       2002  179533
280          Isuzu                  Trooper       1992  154383
281            GMC                   Savana       2007  122158
282          Mazda                  Protege       1998  151177
283          Acura                       CL       2003  173681
284           Ford         F-250 Super Duty       2006  139681
285         Saturn                 S-Series       2000  160211
286        Pontiac                       G6       2005  156916
287     Mitsubishi                  Eclipse       2010  195227
288           Audi                      RS4       2008  183669
289         Toyota                    Camry       1995  144579
290       Infiniti                        I       1998  185101
291        Porsche                      911       2006  174162
292       Plymouth                  Acclaim       1994  163893
293        Hyundai                   Tucson       2012  167239
294       Chrysler                  Sebring       2000  153304
295          Dodge                   Shadow       1994  133954
296        Pontiac               Bonneville       1990  130266
297         Nissan                     350Z       2009  101341
298     Volkswagen                   Type 2       1990  120340
299           Ford           Econoline E150       2000  150993
300           Audi                       A4       2009  126828
301  Mercedes-Benz                  C-Class       1997  107652
302            Kia                   Optima       2009  133607
303          Dodge                 Ram 3500       2003  177367
304           Ford                   Ranger       2006  151539
305           Jeep           Grand Cherokee       2001  109879
306      Chevrolet             Express 3500       2008  110412
307         Nissan                   Xterra       2011  117356
308           Saab                      9-3       2004  167603
309          Dodge             Ram Van B150       1993  106751
310        Lincoln                Navigator       2005  195302
311          Dodge                     Neon       1998  123895
312      Chevrolet             Express 1500       2012  190243
313        Bentley                    Azure       2009  177731
314           Ford                   Fusion       2011  161005
315          Isuzu                   Hombre       1996  166040